language: julia
os:
  - linux
julia:
  - 0.4
notifications:
  email: false
sudo: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Bloomberg"); Pkg.test("Bloomberg", coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Bloomberg")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
